### ISSUE TITLE
SequenceMatcher $junkCallback

### ISSUE THREAD

**Issue by JBlond** [JBlond/php-diff#40]
the $junkCallback parameter is never used in the SequenceMatcher  class.
So the lines 193 - 207 (chainB function)

Maybe that can be removed for good.

**Comment by JBlond** [comment]
See PR https://github.com/JBlond/php-diff/pull/41

**Comment by DigiLive** [comment]
It can be removed, because `Diff` currently only calls the `SequenceMatchter` without a 4th parameter.
In other words, the callback functionality isn't implemented into php-diff.

However, the callback functionality of `SequenceMatcher::chainB()` might be a nice feature...

`SequenceMatcher::chainB()` evaluates which lines of the second sequence are repeated enough to mark them as "popular".
These lines are stored in a "popular" dictionary or else in a "nonJunk" dictionary.

The callback allows a user to define a custom function which does the opposite.
`SequenceMatcher::chainB()` passes the same lines as above to this callback function which in turn can also evaluate them.
When the line is considered to be "junk", the callback function should return a thruthy or otherwise a falsy.

If the callback function returns a thruthy (line is junk), `SequenceMatcher::chainB` will move the line from the "popular" dictionary and from the "nonJunk" dictionary to the "junk" dictionary.

Later on `SequenceMatcher::findLongestMatch()` uses this "junk" dictionary.
But here it's getting tricky and I'm not (yet) really sure what happens. 😅
This because of the sequenceMatcher originally being designed for character sequences and not for line sequences as php-diff uses it.

My advice is not to remove code related to this callback from `SequenceMatcher`.
First find out what `SequenceMatcher::findLongestMatch()` exactly does with it.

If it adds value to php-diff, implement the callback feature into  `Diff`.
E.g. Add a new property in which a function reference or closure can be defined and pass this property to `SequenceMatcher` as 4th parameter at its construction.
If it doesn't add value, it can be removed later on.

Please feel free to contact me when you have any questions or comments about above.

**Comment by JBlond** [comment]
@DigiLive Maybe to understand this better it might help to read the the original https://github.com/python/cpython/blob/3.8/Lib/difflib.py
